export const SET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const UPDATED_CONTACT = 'UPDATED_CONTACT';
export const DELETED_CONTACT = 'DELETED_CONTACT';
export const SET_ALL_GROUPS = 'GET_ALL_GROUPS';
export const ADD_GROUP = 'ADD_GROUP';
export const UPDATED_GROUP = 'UPDATED_GROUP';
export const DELETED_GROUP = 'DELETED_GROUP';

